#!/usr/bin/env python

import sys
if len(sys.argv) != 3:
    print 'Usage:', sys.argv[0], 'inputfile outputfile'
    sys.exit(2)

infile = sys.argv[1]
outfile = sys.argv[2]

import tempfile, os
tfname = tempfile.mktemp()
try:
    stylesheet = 'coasim_to_dot.xsl'
    xslt_cmd = 'xsltproc %s %s > %s.dot' % (stylesheet,infile,tfname)
    dot_cmd = 'dot -Tps -o %s %s.dot' % (outfile,tfname)
    res = os.system(xslt_cmd)
    if res != 0:
        print 'Error translating xml to dot'
        sys.exit(2)
    res = os.system(dot_cmd)
    if res != 0:
        print 'Error translating dot-file to PostScript'
        sys.exit(2)
finally:
    os.unlink(tfname)

